---
abstract: 'Calculate the Jaccard Similarity Coefficient of 2 sets'
author:
  - 'Mark Leighton Fisher <fishe116@purdue.edu>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Set-Jaccard-SimilarityCoefficient
requires:
  perl: 5.008008
version: 0.5.1
x_contributors:
  - 'Mark Leighton Fisher <markleightonfisher@gmail.com>'
